import { Navigation } from "@/components/navigation"
import { Footer } from "@/components/footer"
import { TrekHero } from "@/components/trek-hero"
import { TrekItinerary } from "@/components/trek-itinerary"
import { TrekInclusions } from "@/components/trek-inclusions"
import { TrekMap } from "@/components/trek-map"
import { TrekFAQ } from "@/components/trek-faq"
import { TrekBooking } from "@/components/trek-booking"
import { notFound } from "next/navigation"

// This would typically come from a database or CMS
const getTrekData = (slug: string) => {
  const treks = {
    "everest-base-camp": {
      id: "everest-base-camp",
      title: "Everest Base Camp Trek",
      subtitle: "The Ultimate Himalayan Adventure",
      image: "https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=1920&h=800&fit=crop",
      duration: "14 days",
      difficulty: "Challenging",
      maxAltitude: "5,364m",
      bestSeason: "March-May, September-November",
      price: "$1,299",
      region: "Everest",
      rating: 4.9,
      reviewCount: 324,
      description:
        "Embark on the world's most famous trek to Everest Base Camp. This challenging yet rewarding journey takes you through the heart of the Khumbu region, home to the legendary Sherpa people and some of the world's highest peaks.",
      highlights: [
        "Stand at Everest Base Camp (5,364m)",
        "Sunrise from Kala Patthar (5,545m)",
        "Visit Tengboche Monastery",
        "Experience Sherpa culture in Namche Bazaar",
        "Cross suspension bridges over deep gorges",
        "See four 8,000m+ peaks: Everest, Lhotse, Cho Oyu, Makalu",
      ],
      inclusions: [
        "Airport transfers in Kathmandu",
        "Domestic flights (Kathmandu-Lukla-Kathmandu)",
        "All meals during the trek (breakfast, lunch, dinner)",
        "Tea house accommodation during the trek",
        "Professional English-speaking guide",
        "Porter service (2 trekkers : 1 porter)",
        "All necessary permits (National Park fees, TIMS)",
        "First aid medical kit",
        "All government and local taxes",
        "Achievement certificate",
        "NepTrek duffel bag and sleeping bag",
        "Comprehensive pre-trek briefing",
      ],
      exclusions: [
        "International airfare to/from Nepal",
        "Nepal visa fees",
        "Hotel accommodation in Kathmandu",
        "Meals in Kathmandu",
        "Personal trekking equipment",
        "Travel and rescue insurance",
        "Personal expenses (phone calls, laundry, bar bills)",
        "Tips for guide and porter",
        "Extra night accommodation due to early arrival/late departure",
        "Helicopter rescue in case of emergency",
        "Any services not mentioned in 'What's Included'",
      ],
      itinerary: [
        {
          day: 1,
          title: "Fly to Lukla, Trek to Phakding",
          altitude: "2,652m",
          duration: "3-4 hours",
          description: "Scenic flight to Lukla airport, begin trek through pine forests to Phakding.",
        },
        {
          day: 2,
          title: "Trek to Namche Bazaar",
          altitude: "3,440m",
          duration: "6-7 hours",
          description: "Cross suspension bridges, steep climb to the Sherpa capital of Namche Bazaar.",
        },
        {
          day: 3,
          title: "Acclimatization Day in Namche",
          altitude: "3,440m",
          duration: "Rest day",
          description: "Explore Namche Bazaar, visit Everest View Hotel, acclimatization hikes.",
        },
        {
          day: 4,
          title: "Trek to Tengboche",
          altitude: "3,867m",
          duration: "5-6 hours",
          description: "Trek through rhododendron forests to famous Tengboche Monastery.",
        },
        {
          day: 5,
          title: "Trek to Dingboche",
          altitude: "4,410m",
          duration: "6-7 hours",
          description: "Enter the alpine zone, spectacular mountain views, arrive at Dingboche.",
        },
        {
          day: 6,
          title: "Acclimatization Day in Dingboche",
          altitude: "4,410m",
          duration: "Rest day",
          description: "Rest day with optional hike to Nagarjun Hill for acclimatization.",
        },
        {
          day: 7,
          title: "Trek to Lobuche",
          altitude: "4,940m",
          duration: "5-6 hours",
          description: "Trek past memorials to climbers, arrive at Lobuche with Everest views.",
        },
        {
          day: 8,
          title: "Trek to EBC and back to Gorak Shep",
          altitude: "5,364m",
          duration: "7-8 hours",
          description: "Early morning trek to Everest Base Camp, return to Gorak Shep.",
        },
        {
          day: 9,
          title: "Kala Patthar and Trek to Pheriche",
          altitude: "5,545m",
          duration: "7-8 hours",
          description: "Pre-dawn hike to Kala Patthar for sunrise, descend to Pheriche.",
        },
        {
          day: 10,
          title: "Trek to Namche Bazaar",
          altitude: "3,440m",
          duration: "6-7 hours",
          description: "Long descent through Tengboche back to Namche Bazaar.",
        },
        {
          day: 11,
          title: "Trek to Lukla",
          altitude: "2,860m",
          duration: "6-7 hours",
          description: "Final day of trekking, return to Lukla for celebration dinner.",
        },
        {
          day: 12,
          title: "Fly to Kathmandu",
          altitude: "1,400m",
          duration: "45 minutes",
          description: "Morning flight back to Kathmandu, rest and explore the city.",
        },
      ],
    },
    "annapurna-circuit": {
      id: "annapurna-circuit",
      title: "Annapurna Circuit Trek",
      subtitle: "Classic Circuit Through Diverse Landscapes",
      image: "https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?w=1920&h=800&fit=crop",
      duration: "16 days",
      difficulty: "Moderate",
      maxAltitude: "5,416m",
      bestSeason: "March-May, September-November",
      price: "$1,199",
      region: "Annapurna",
      rating: 4.8,
      reviewCount: 256,
      description:
        "The classic Annapurna Circuit offers incredible diversity - from subtropical forests to high alpine desert, crossing the famous Thorong La Pass at 5,416m.",
      highlights: [
        "Cross Thorong La Pass (5,416m)",
        "Visit sacred Muktinath Temple",
        "Sunrise from Poon Hill",
        "Hot springs at Tatopani",
        "Diverse landscapes and cultures",
        "360° mountain panoramas",
      ],
      inclusions: [
        "Airport transfers in Kathmandu",
        "Private vehicle to trek starting point",
        "All meals during the trek",
        "Tea house accommodation",
        "Professional guide and porter",
        "All permits and fees",
        "First aid kit",
        "Government taxes",
      ],
      exclusions: [
        "International flights",
        "Nepal visa",
        "Kathmandu accommodation",
        "Personal equipment",
        "Insurance",
        "Personal expenses",
        "Tips",
        "Emergency evacuation",
      ],
      itinerary: [
        {
          day: 1,
          title: "Drive to Besisahar, Trek to Bhulbhule",
          altitude: "840m",
          duration: "6-7 hours",
          description: "Drive to Besisahar, begin trek along Marsyangdi River.",
        },
        {
          day: 2,
          title: "Trek to Jagat",
          altitude: "1,300m",
          duration: "6-7 hours",
          description: "Trek through terraced fields and traditional villages.",
        },
        {
          day: 3,
          title: "Trek to Dharapani",
          altitude: "1,860m",
          duration: "6-7 hours",
          description: "Enter the restricted area, Tibetan influence begins.",
        },
        {
          day: 4,
          title: "Trek to Chame",
          altitude: "2,670m",
          duration: "5-6 hours",
          description: "District headquarters of Manang, hot springs available.",
        },
        {
          day: 5,
          title: "Trek to Pisang",
          altitude: "3,200m",
          duration: "5-6 hours",
          description: "Enter the Manang valley, spectacular mountain views.",
        },
        {
          day: 6,
          title: "Trek to Manang",
          altitude: "3,519m",
          duration: "6-7 hours",
          description: "Beautiful valley with traditional Tibetan culture.",
        },
        {
          day: 7,
          title: "Acclimatization Day in Manang",
          altitude: "3,519m",
          duration: "Rest day",
          description: "Rest day with optional hikes for acclimatization.",
        },
        {
          day: 8,
          title: "Trek to Yak Kharka",
          altitude: "4,018m",
          duration: "4-5 hours",
          description: "Gradual ascent through alpine meadows.",
        },
        {
          day: 9,
          title: "Trek to Thorong Phedi",
          altitude: "4,450m",
          duration: "3-4 hours",
          description: "Base camp for Thorong La Pass crossing.",
        },
        {
          day: 10,
          title: "Cross Thorong La Pass to Muktinath",
          altitude: "5,416m",
          duration: "7-8 hours",
          description: "Early morning pass crossing, visit sacred Muktinath Temple.",
        },
        {
          day: 11,
          title: "Trek to Marpha",
          altitude: "2,667m",
          duration: "4-5 hours",
          description: "Descent through Kali Gandaki valley, apple orchards.",
        },
        {
          day: 12,
          title: "Trek to Tatopani",
          altitude: "1,190m",
          duration: "6-7 hours",
          description: "Natural hot springs, deepest gorge in the world.",
        },
        {
          day: 13,
          title: "Trek to Ghorepani",
          altitude: "2,874m",
          duration: "7-8 hours",
          description: "Steep climb through rhododendron forests.",
        },
        {
          day: 14,
          title: "Poon Hill Sunrise, Trek to Tadapani",
          altitude: "2,630m",
          duration: "6-7 hours",
          description: "Early morning Poon Hill sunrise, trek to Tadapani.",
        },
        {
          day: 15,
          title: "Trek to Ghandruk",
          altitude: "1,940m",
          duration: "3-4 hours",
          description: "Beautiful Gurung village with mountain views.",
        },
        {
          day: 16,
          title: "Trek to Nayapul, Drive to Pokhara",
          altitude: "1,070m",
          duration: "5-6 hours",
          description: "Final day of trekking, drive to Pokhara.",
        },
      ],
    },
    "langtang-valley": {
      id: "langtang-valley",
      title: "Langtang Valley Trek",
      subtitle: "Pristine Valley with Rich Tamang Culture",
      image: "https://images.unsplash.com/photo-1605540436563-5bca919ae766?w=1920&h=800&fit=crop",
      duration: "10 days",
      difficulty: "Moderate",
      maxAltitude: "4,984m",
      bestSeason: "March-May, September-November",
      price: "$899",
      region: "Langtang",
      rating: 4.7,
      reviewCount: 189,
      description:
        "Discover the pristine Langtang Valley, known as the 'Valley of Glaciers', with rich Tamang culture and stunning mountain views close to Kathmandu.",
      highlights: [
        "Kyanjin Gompa monastery",
        "Langtang Lirung views (7,227m)",
        "Traditional Tamang villages",
        "Cheese factory visit",
        "Tserko Ri viewpoint (4,984m)",
        "Close to Kathmandu",
      ],
      inclusions: [
        "Airport transfers",
        "Private vehicle to Syabrubesi",
        "All meals during trek",
        "Tea house accommodation",
        "Professional guide and porter",
        "All permits and fees",
        "First aid kit",
        "Government taxes",
      ],
      exclusions: [
        "International flights",
        "Nepal visa",
        "Kathmandu accommodation",
        "Personal equipment",
        "Insurance",
        "Personal expenses",
        "Tips",
        "Emergency evacuation",
      ],
      itinerary: [
        {
          day: 1,
          title: "Drive to Syabrubesi",
          altitude: "1,550m",
          duration: "7-8 hours",
          description: "Scenic drive through terraced hills to Syabrubesi.",
        },
        {
          day: 2,
          title: "Trek to Lama Hotel",
          altitude: "2,380m",
          duration: "6-7 hours",
          description: "Trek through dense forests along Langtang River.",
        },
        {
          day: 3,
          title: "Trek to Langtang Village",
          altitude: "3,430m",
          duration: "6-7 hours",
          description: "Enter Langtang Valley, traditional Tamang village.",
        },
        {
          day: 4,
          title: "Trek to Kyanjin Gompa",
          altitude: "3,870m",
          duration: "3-4 hours",
          description: "Reach Kyanjin Gompa, visit cheese factory and monastery.",
        },
        {
          day: 5,
          title: "Explore Kyanjin Gompa",
          altitude: "3,870m",
          duration: "Rest day",
          description: "Rest day with optional hikes to Tserko Ri or Kyanjin Ri.",
        },
        {
          day: 6,
          title: "Trek to Lama Hotel",
          altitude: "2,380m",
          duration: "6-7 hours",
          description: "Retrace steps back to Lama Hotel.",
        },
        {
          day: 7,
          title: "Trek to Thulo Syabru",
          altitude: "2,230m",
          duration: "5-6 hours",
          description: "Alternative route through beautiful forests.",
        },
        {
          day: 8,
          title: "Trek to Sing Gompa",
          altitude: "3,330m",
          duration: "4-5 hours",
          description: "Climb to Sing Gompa through rhododendron forests.",
        },
        {
          day: 9,
          title: "Trek to Gosaikunda and back to Sing Gompa",
          altitude: "4,380m",
          duration: "6-7 hours",
          description: "Visit sacred Gosaikunda lakes, return to Sing Gompa.",
        },
        {
          day: 10,
          title: "Trek to Dhunche, Drive to Kathmandu",
          altitude: "1,960m",
          duration: "7-8 hours",
          description: "Final trek to Dhunche, drive back to Kathmandu.",
        },
      ],
    },
    "manaslu-circuit": {
      id: "manaslu-circuit",
      title: "Manaslu Circuit Trek",
      subtitle: "Off-the-Beaten-Path Adventure",
      image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1920&h=800&fit=crop",
      duration: "18 days",
      difficulty: "Challenging",
      maxAltitude: "5,106m",
      bestSeason: "March-May, September-November",
      price: "$1,499",
      region: "Manaslu",
      rating: 4.9,
      reviewCount: 142,
      description:
        "Trek around Manaslu, the world's eighth highest peak, through remote villages and pristine wilderness with fewer crowds than other popular routes.",
      highlights: [
        "Larkya La Pass (5,106m)",
        "Manaslu Base Camp views",
        "Remote Tibetan villages",
        "Samagaon monastery",
        "Pristine wilderness",
        "Fewer crowds",
      ],
      inclusions: [
        "Airport transfers",
        "Private vehicle to trek start",
        "All meals during trek",
        "Tea house/camping accommodation",
        "Professional guide and porter",
        "Restricted area permits",
        "All fees and taxes",
        "First aid kit",
      ],
      exclusions: [
        "International flights",
        "Nepal visa",
        "Kathmandu accommodation",
        "Personal equipment",
        "Insurance",
        "Personal expenses",
        "Tips",
        "Emergency evacuation",
      ],
      itinerary: [
        {
          day: 1,
          title: "Drive to Soti Khola",
          altitude: "700m",
          duration: "8-9 hours",
          description: "Long drive to trek starting point at Soti Khola.",
        },
        {
          day: 2,
          title: "Trek to Machha Khola",
          altitude: "930m",
          duration: "6-7 hours",
          description: "Trek along Budhi Gandaki River through terraced fields.",
        },
        {
          day: 3,
          title: "Trek to Jagat",
          altitude: "1,340m",
          duration: "6-7 hours",
          description: "Continue along river, cross suspension bridges.",
        },
        {
          day: 4,
          title: "Trek to Deng",
          altitude: "1,804m",
          duration: "6-7 hours",
          description: "Enter restricted area, Tibetan influence begins.",
        },
        {
          day: 5,
          title: "Trek to Namrung",
          altitude: "2,630m",
          duration: "6-7 hours",
          description: "First views of Manaslu, traditional villages.",
        },
        {
          day: 6,
          title: "Trek to Samagaon",
          altitude: "3,530m",
          duration: "4-5 hours",
          description: "Beautiful village with monastery and Manaslu views.",
        },
        {
          day: 7,
          title: "Acclimatization Day in Samagaon",
          altitude: "3,530m",
          duration: "Rest day",
          description: "Rest day with optional hikes for acclimatization.",
        },
        {
          day: 8,
          title: "Trek to Samdo",
          altitude: "3,875m",
          duration: "4-5 hours",
          description: "Tibetan village near Tibet border.",
        },
        {
          day: 9,
          title: "Acclimatization Day in Samdo",
          altitude: "3,875m",
          duration: "Rest day",
          description: "Rest day with optional border viewpoint hike.",
        },
        {
          day: 10,
          title: "Trek to Dharamsala",
          altitude: "4,460m",
          duration: "4-5 hours",
          description: "Base camp for Larkya La Pass crossing.",
        },
        {
          day: 11,
          title: "Cross Larkya La Pass to Bimthang",
          altitude: "5,106m",
          duration: "8-9 hours",
          description: "Early morning pass crossing, spectacular mountain views.",
        },
        {
          day: 12,
          title: "Trek to Tilije",
          altitude: "2,300m",
          duration: "5-6 hours",
          description: "Descent through different landscape and culture.",
        },
        {
          day: 13,
          title: "Trek to Tal",
          altitude: "1,700m",
          duration: "5-6 hours",
          description: "Join Annapurna Circuit route at Tal.",
        },
        {
          day: 14,
          title: "Trek to Syange",
          altitude: "1,100m",
          duration: "6-7 hours",
          description: "Continue descent along Marsyangdi River.",
        },
        {
          day: 15,
          title: "Drive to Kathmandu",
          altitude: "1,400m",
          duration: "8-9 hours",
          description: "Long drive back to Kathmandu via Besisahar.",
        },
      ],
    },
    "gokyo-lakes": {
      id: "gokyo-lakes",
      title: "Gokyo Lakes Trek",
      subtitle: "Stunning Alpine Lakes with Everest Views",
      image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1920&h=800&fit=crop&sat=20&hue=180",
      duration: "12 days",
      difficulty: "Moderate",
      maxAltitude: "5,357m",
      bestSeason: "March-May, September-November",
      price: "$1,149",
      region: "Everest",
      rating: 4.8,
      reviewCount: 198,
      description:
        "Trek to the stunning turquoise Gokyo Lakes and climb Gokyo Ri for panoramic views of Everest, Lhotse, Makalu, and Cho Oyu.",
      highlights: [
        "Six sacred Gokyo Lakes",
        "Gokyo Ri summit (5,357m)",
        "Panoramic Everest views",
        "Cho Oyu Base Camp option",
        "Ngozumpa Glacier",
        "Less crowded than EBC",
      ],
      inclusions: [
        "Airport transfers",
        "Lukla flights",
        "All meals during trek",
        "Tea house accommodation",
        "Professional guide and porter",
        "All permits and fees",
        "First aid kit",
        "Government taxes",
      ],
      exclusions: [
        "International flights",
        "Nepal visa",
        "Kathmandu accommodation",
        "Personal equipment",
        "Insurance",
        "Personal expenses",
        "Tips",
        "Emergency evacuation",
      ],
      itinerary: [
        {
          day: 1,
          title: "Fly to Lukla, Trek to Phakding",
          altitude: "2,652m",
          duration: "3-4 hours",
          description: "Scenic flight to Lukla, begin trek to Phakding.",
        },
        {
          day: 2,
          title: "Trek to Namche Bazaar",
          altitude: "3,440m",
          duration: "6-7 hours",
          description: "Steep climb to Sherpa capital Namche Bazaar.",
        },
        {
          day: 3,
          title: "Acclimatization Day in Namche",
          altitude: "3,440m",
          duration: "Rest day",
          description: "Rest day with optional acclimatization hikes.",
        },
        {
          day: 4,
          title: "Trek to Dole",
          altitude: "4,200m",
          duration: "5-6 hours",
          description: "Trek up Gokyo valley through rhododendron forests.",
        },
        {
          day: 5,
          title: "Trek to Machhermo",
          altitude: "4,470m",
          duration: "4-5 hours",
          description: "Continue up valley with increasing mountain views.",
        },
        {
          day: 6,
          title: "Trek to Gokyo",
          altitude: "4,790m",
          duration: "4-5 hours",
          description: "Reach Gokyo village beside the sacred lakes.",
        },
        {
          day: 7,
          title: "Gokyo Ri and Fifth Lake",
          altitude: "5,357m",
          duration: "6-7 hours",
          description: "Climb Gokyo Ri for sunrise, visit fifth lake.",
        },
        {
          day: 8,
          title: "Trek to Dole",
          altitude: "4,200m",
          duration: "4-5 hours",
          description: "Begin descent back down the valley.",
        },
        {
          day: 9,
          title: "Trek to Namche Bazaar",
          altitude: "3,440m",
          duration: "5-6 hours",
          description: "Return to Namche Bazaar for rest.",
        },
        {
          day: 10,
          title: "Trek to Lukla",
          altitude: "2,860m",
          duration: "6-7 hours",
          description: "Final day of trekking back to Lukla.",
        },
        {
          day: 11,
          title: "Fly to Kathmandu",
          altitude: "1,400m",
          duration: "45 minutes",
          description: "Morning flight back to Kathmandu.",
        },
      ],
    },
    "upper-mustang": {
      id: "upper-mustang",
      title: "Upper Mustang Trek",
      subtitle: "Journey to the Forbidden Kingdom",
      image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1920&h=800&fit=crop&sat=-30&hue=30",
      duration: "14 days",
      difficulty: "Moderate",
      maxAltitude: "4,000m",
      bestSeason: "March-November",
      price: "$1,399",
      region: "Mustang",
      rating: 4.6,
      reviewCount: 87,
      description:
        "Explore the ancient kingdom of Mustang with its unique Tibetan culture, desert landscapes, and medieval walled city of Lo Manthang.",
      highlights: [
        "Lo Manthang walled city",
        "Ancient cave monasteries",
        "Tibetan Buddhist culture",
        "Desert landscapes",
        "Royal palace visit",
        "Year-round trekking",
      ],
      inclusions: [
        "Airport transfers",
        "Pokhara flights",
        "All meals during trek",
        "Tea house accommodation",
        "Professional guide and porter",
        "Restricted area permits",
        "All fees and taxes",
        "First aid kit",
      ],
      exclusions: [
        "International flights",
        "Nepal visa",
        "Hotel accommodation",
        "Personal equipment",
        "Insurance",
        "Personal expenses",
        "Tips",
        "Emergency evacuation",
      ],
      itinerary: [
        {
          day: 1,
          title: "Fly to Jomsom",
          altitude: "2,720m",
          duration: "25 minutes",
          description: "Scenic flight from Pokhara to Jomsom.",
        },
        {
          day: 2,
          title: "Trek to Charang",
          altitude: "3,560m",
          duration: "6-7 hours",
          description: "Trek through Kali Gandaki valley to Charang.",
        },
        {
          day: 3,
          title: "Trek to Lo Manthang",
          altitude: "3,840m",
          duration: "4-5 hours",
          description: "Reach the walled city of Lo Manthang.",
        },
        {
          day: 4,
          title: "Explore Lo Manthang",
          altitude: "3,840m",
          duration: "Full day",
          description: "Explore the ancient capital and royal palace.",
        },
        {
          day: 5,
          title: "Trek to Dhakmar",
          altitude: "3,820m",
          duration: "6-7 hours",
          description: "Trek through unique red cliff formations.",
        },
        {
          day: 6,
          title: "Trek to Syangmochen",
          altitude: "3,800m",
          duration: "5-6 hours",
          description: "Continue through high desert landscape.",
        },
        {
          day: 7,
          title: "Trek to Ghami",
          altitude: "3,520m",
          duration: "5-6 hours",
          description: "Visit ancient monasteries and chortens.",
        },
        {
          day: 8,
          title: "Trek to Tsarang",
          altitude: "3,560m",
          duration: "4-5 hours",
          description: "Explore Tsarang monastery and palace.",
        },
        {
          day: 9,
          title: "Trek to Lo Manthang",
          altitude: "3,840m",
          duration: "3-4 hours",
          description: "Return to Lo Manthang for second visit.",
        },
        {
          day: 10,
          title: "Trek to Ghami",
          altitude: "3,520m",
          duration: "6-7 hours",
          description: "Begin journey back south.",
        },
        {
          day: 11,
          title: "Trek to Samar",
          altitude: "3,660m",
          duration: "5-6 hours",
          description: "Trek through traditional villages.",
        },
        {
          day: 12,
          title: "Trek to Jomsom",
          altitude: "2,720m",
          duration: "6-7 hours",
          description: "Final day of trekking back to Jomsom.",
        },
        {
          day: 13,
          title: "Fly to Pokhara",
          altitude: "822m",
          duration: "25 minutes",
          description: "Morning flight back to Pokhara.",
        },
      ],
    },
    "annapurna-base-camp": {
      id: "annapurna-base-camp",
      title: "Annapurna Base Camp Trek",
      subtitle: "Into the Heart of the Annapurna Sanctuary",
      image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1920&h=800&fit=crop&sat=10&hue=200",
      duration: "12 days",
      difficulty: "Moderate",
      maxAltitude: "4,130m",
      bestSeason: "March-May, September-November",
      price: "$999",
      region: "Annapurna",
      rating: 4.7,
      reviewCount: 267,
      description:
        "Trek into the spectacular Annapurna Sanctuary, surrounded by towering peaks including Annapurna I, Machapuchare, and Hiunchuli.",
      highlights: [
        "Annapurna Sanctuary amphitheater",
        "Machapuchare (Fishtail) views",
        "Natural hot springs",
        "Diverse ecosystems",
        "Gurung and Magar culture",
        "360° mountain panorama",
      ],
      inclusions: [
        "Airport transfers",
        "Private vehicle to trek start",
        "All meals during trek",
        "Tea house accommodation",
        "Professional guide and porter",
        "All permits and fees",
        "First aid kit",
        "Government taxes",
      ],
      exclusions: [
        "International flights",
        "Nepal visa",
        "Hotel accommodation",
        "Personal equipment",
        "Insurance",
        "Personal expenses",
        "Tips",
        "Emergency evacuation",
      ],
      itinerary: [
        {
          day: 1,
          title: "Drive to Nayapul, Trek to Tikhedhunga",
          altitude: "1,577m",
          duration: "4-5 hours",
          description: "Drive to Nayapul, begin trek to Tikhedhunga.",
        },
        {
          day: 2,
          title: "Trek to Ghorepani",
          altitude: "2,874m",
          duration: "6-7 hours",
          description: "Steep climb through rhododendron forests.",
        },
        {
          day: 3,
          title: "Poon Hill Sunrise, Trek to Tadapani",
          altitude: "2,630m",
          duration: "6-7 hours",
          description: "Early morning Poon Hill sunrise, trek to Tadapani.",
        },
        {
          day: 4,
          title: "Trek to Chhomrong",
          altitude: "2,170m",
          duration: "5-6 hours",
          description: "Descend and climb to Gurung village of Chhomrong.",
        },
        {
          day: 5,
          title: "Trek to Bamboo",
          altitude: "2,310m",
          duration: "5-6 hours",
          description: "Descend into Modi Khola valley, dense forests.",
        },
        {
          day: 6,
          title: "Trek to Deurali",
          altitude: "3,230m",
          duration: "4-5 hours",
          description: "Continue up valley, enter alpine zone.",
        },
        {
          day: 7,
          title: "Trek to Annapurna Base Camp",
          altitude: "4,130m",
          duration: "4-5 hours",
          description: "Reach ABC, surrounded by towering peaks.",
        },
        {
          day: 8,
          title: "Trek to Bamboo",
          altitude: "2,310m",
          duration: "6-7 hours",
          description: "Begin descent from base camp.",
        },
        {
          day: 9,
          title: "Trek to Jhinu Danda",
          altitude: "1,780m",
          duration: "5-6 hours",
          description: "Trek to hot springs at Jhinu Danda.",
        },
        {
          day: 10,
          title: "Trek to Nayapul, Drive to Pokhara",
          altitude: "1,070m",
          duration: "5-6 hours",
          description: "Final day of trekking, drive to Pokhara.",
        },
      ],
    },
    "mardi-himal": {
      id: "mardi-himal",
      title: "Mardi Himal Trek",
      subtitle: "Hidden Gem with Spectacular Views",
      image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1920&h=800&fit=crop&sat=15&hue=220",
      duration: "8 days",
      difficulty: "Easy",
      maxAltitude: "4,500m",
      bestSeason: "March-May, September-November",
      price: "$699",
      region: "Annapurna",
      rating: 4.5,
      reviewCount: 156,
      description:
        "Discover the hidden gem of Mardi Himal with spectacular mountain views, fewer crowds, and pristine forest trails.",
      highlights: [
        "Mardi Himal Base Camp",
        "Machapuchare close views",
        "Forest ridge walking",
        "Fewer crowds",
        "Mountain panoramas",
        "Short duration trek",
      ],
      inclusions: [
        "Airport transfers",
        "Private vehicle transport",
        "All meals during trek",
        "Tea house accommodation",
        "Professional guide and porter",
        "All permits and fees",
        "First aid kit",
        "Government taxes",
      ],
      exclusions: [
        "International flights",
        "Nepal visa",
        "Hotel accommodation",
        "Personal equipment",
        "Insurance",
        "Personal expenses",
        "Tips",
        "Emergency evacuation",
      ],
      itinerary: [
        {
          day: 1,
          title: "Drive to Kande, Trek to Forest Camp",
          altitude: "2,520m",
          duration: "4-5 hours",
          description: "Drive to Kande, trek through forests to Forest Camp.",
        },
        {
          day: 2,
          title: "Trek to Low Camp",
          altitude: "2,990m",
          duration: "4-5 hours",
          description: "Continue through rhododendron forests to Low Camp.",
        },
        {
          day: 3,
          title: "Trek to High Camp",
          altitude: "3,580m",
          duration: "3-4 hours",
          description: "Emerge above treeline with spectacular mountain views.",
        },
        {
          day: 4,
          title: "Trek to Mardi Himal Base Camp",
          altitude: "4,500m",
          duration: "4-5 hours",
          description: "Reach base camp with close-up Machapuchare views.",
        },
        {
          day: 5,
          title: "Trek to Low Camp",
          altitude: "2,990m",
          duration: "5-6 hours",
          description: "Begin descent back through High Camp.",
        },
        {
          day: 6,
          title: "Trek to Siding Village",
          altitude: "1,750m",
          duration: "4-5 hours",
          description: "Descend to traditional Gurung village.",
        },
        {
          day: 7,
          title: "Trek to Lumre, Drive to Pokhara",
          altitude: "1,560m",
          duration: "4-5 hours",
          description: "Final day of trekking, drive to Pokhara.",
        },
      ],
    },
    "poon-hill": {
      id: "poon-hill",
      title: "Poon Hill Trek",
      subtitle: "Perfect Introduction to Himalayan Trekking",
      image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1920&h=800&fit=crop&sat=25&hue=40",
      duration: "5 days",
      difficulty: "Easy",
      maxAltitude: "3,210m",
      bestSeason: "March-May, September-December",
      price: "$499",
      region: "Annapurna",
      rating: 4.6,
      reviewCount: 423,
      description:
        "Perfect introduction to Himalayan trekking with stunning sunrise views from Poon Hill and beautiful rhododendron forests.",
      highlights: [
        "Poon Hill sunrise viewpoint",
        "Rhododendron forests",
        "Gurung villages",
        "Annapurna and Dhaulagiri views",
        "Short and easy trek",
        "Year-round accessibility",
      ],
      inclusions: [
        "Airport transfers",
        "Private vehicle transport",
        "All meals during trek",
        "Tea house accommodation",
        "Professional guide and porter",
        "All permits and fees",
        "First aid kit",
        "Government taxes",
      ],
      exclusions: [
        "International flights",
        "Nepal visa",
        "Hotel accommodation",
        "Personal equipment",
        "Insurance",
        "Personal expenses",
        "Tips",
        "Emergency evacuation",
      ],
      itinerary: [
        {
          day: 1,
          title: "Drive to Nayapul, Trek to Tikhedhunga",
          altitude: "1,577m",
          duration: "4-5 hours",
          description: "Drive to Nayapul, begin trek to Tikhedhunga.",
        },
        {
          day: 2,
          title: "Trek to Ghorepani",
          altitude: "2,874m",
          duration: "6-7 hours",
          description: "Steep climb through beautiful rhododendron forests.",
        },
        {
          day: 3,
          title: "Poon Hill Sunrise, Trek to Tadapani",
          altitude: "2,630m",
          duration: "6-7 hours",
          description: "Early morning Poon Hill sunrise, trek to Tadapani.",
        },
        {
          day: 4,
          title: "Trek to Ghandruk",
          altitude: "1,940m",
          duration: "3-4 hours",
          description: "Descend to beautiful Gurung village of Ghandruk.",
        },
        {
          day: 5,
          title: "Trek to Nayapul, Drive to Pokhara",
          altitude: "1,070m",
          duration: "4-5 hours",
          description: "Final day of trekking, drive back to Pokhara.",
        },
      ],
    },
    "everest-three-passes": {
      id: "everest-three-passes",
      title: "Everest Three Passes Trek",
      subtitle: "Ultimate Everest Region Challenge",
      image: "https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=1920&h=800&fit=crop&sat=10&hue=210",
      duration: "21 days",
      difficulty: "Strenuous",
      maxAltitude: "5,545m",
      bestSeason: "March-May, September-November",
      price: "$1,899",
      region: "Everest",
      rating: 4.9,
      reviewCount: 89,
      description:
        "The ultimate Everest region challenge, crossing three high altitude passes: Renjo La, Cho La, and Kongma La, plus visiting both EBC and Gokyo Lakes.",
      highlights: [
        "Three high passes crossing",
        "Everest Base Camp",
        "Gokyo Lakes and Gokyo Ri",
        "Kala Patthar sunrise",
        "Island Peak option",
        "Complete Everest circuit",
      ],
      inclusions: [
        "Airport transfers",
        "Lukla flights",
        "All meals during trek",
        "Tea house accommodation",
        "Professional guide and porter",
        "All permits and fees",
        "First aid kit",
        "Government taxes",
      ],
      exclusions: [
        "International flights",
        "Nepal visa",
        "Kathmandu accommodation",
        "Personal equipment",
        "Insurance",
        "Personal expenses",
        "Tips",
        "Emergency evacuation",
      ],
      itinerary: [
        {
          day: 1,
          title: "Fly to Lukla, Trek to Phakding",
          altitude: "2,652m",
          duration: "3-4 hours",
          description: "Scenic flight to Lukla, begin trek to Phakding.",
        },
        {
          day: 2,
          title: "Trek to Namche Bazaar",
          altitude: "3,440m",
          duration: "6-7 hours",
          description: "Steep climb to Sherpa capital Namche Bazaar.",
        },
        {
          day: 3,
          title: "Acclimatization Day in Namche",
          altitude: "3,440m",
          duration: "Rest day",
          description: "Rest day with optional acclimatization hikes.",
        },
        {
          day: 4,
          title: "Trek to Tengboche",
          altitude: "3,867m",
          duration: "5-6 hours",
          description: "Trek to famous Tengboche Monastery.",
        },
        {
          day: 5,
          title: "Trek to Dingboche",
          altitude: "4,410m",
          duration: "6-7 hours",
          description: "Enter alpine zone, spectacular mountain views.",
        },
        {
          day: 6,
          title: "Acclimatization Day in Dingboche",
          altitude: "4,410m",
          duration: "Rest day",
          description: "Rest day with optional Nagarjun Hill hike.",
        },
        {
          day: 7,
          title: "Trek to Chukhung",
          altitude: "4,730m",
          duration: "3-4 hours",
          description: "Short trek to Chukhung for acclimatization.",
        },
        {
          day: 8,
          title: "Cross Kongma La Pass to Lobuche",
          altitude: "5,535m",
          duration: "8-9 hours",
          description: "First pass crossing, technical sections with views.",
        },
        {
          day: 9,
          title: "Trek to EBC and back to Gorak Shep",
          altitude: "5,364m",
          duration: "7-8 hours",
          description: "Trek to Everest Base Camp, return to Gorak Shep.",
        },
        {
          day: 10,
          title: "Kala Patthar and Trek to Dzongla",
          altitude: "5,545m",
          duration: "7-8 hours",
          description: "Pre-dawn Kala Patthar climb, trek to Dzongla.",
        },
        {
          day: 11,
          title: "Cross Cho La Pass to Thangnak",
          altitude: "5,420m",
          duration: "7-8 hours",
          description: "Second pass crossing, glacier walking required.",
        },
        {
          day: 12,
          title: "Trek to Gokyo",
          altitude: "4,790m",
          duration: "3-4 hours",
          description: "Reach beautiful Gokyo Lakes.",
        },
        {
          day: 13,
          title: "Gokyo Ri and Fifth Lake",
          altitude: "5,357m",
          duration: "6-7 hours",
          description: "Climb Gokyo Ri for sunrise, visit fifth lake.",
        },
        {
          day: 14,
          title: "Cross Renjo La Pass to Lungden",
          altitude: "5,340m",
          duration: "7-8 hours",
          description: "Third pass crossing with spectacular views.",
        },
        {
          day: 15,
          title: "Trek to Thame",
          altitude: "3,820m",
          duration: "4-5 hours",
          description: "Descend to traditional Sherpa village of Thame.",
        },
        {
          day: 16,
          title: "Trek to Namche Bazaar",
          altitude: "3,440m",
          duration: "4-5 hours",
          description: "Return to Namche Bazaar for rest.",
        },
        {
          day: 17,
          title: "Trek to Lukla",
          altitude: "2,860m",
          duration: "6-7 hours",
          description: "Final day of trekking back to Lukla.",
        },
        {
          day: 18,
          title: "Fly to Kathmandu",
          altitude: "1,400m",
          duration: "45 minutes",
          description: "Morning flight back to Kathmandu.",
        },
      ],
    },
    "tsum-valley": {
      id: "tsum-valley",
      title: "Tsum Valley Trek",
      subtitle: "Hidden Sacred Valley",
      image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1920&h=800&fit=crop&sat=5&hue=120",
      duration: "16 days",
      difficulty: "Moderate",
      maxAltitude: "3,700m",
      bestSeason: "March-May, September-November",
      price: "$1,299",
      region: "Manaslu",
      rating: 4.7,
      reviewCount: 67,
      description:
        "Explore the hidden sacred valley of Tsum with ancient Tibetan Buddhist culture, pristine nature, and warm hospitality of local people.",
      highlights: [
        "Mu Gompa monastery",
        "Ancient Tibetan culture",
        "Sacred valley pilgrimage",
        "Pristine wilderness",
        "Traditional villages",
        "Restricted area permit",
      ],
      inclusions: [
        "Airport transfers",
        "Private vehicle transport",
        "All meals during trek",
        "Tea house accommodation",
        "Professional guide and porter",
        "Restricted area permits",
        "All fees and taxes",
        "First aid kit",
      ],
      exclusions: [
        "International flights",
        "Nepal visa",
        "Hotel accommodation",
        "Personal equipment",
        "Insurance",
        "Personal expenses",
        "Tips",
        "Emergency evacuation",
      ],
      itinerary: [
        {
          day: 1,
          title: "Drive to Soti Khola",
          altitude: "700m",
          duration: "8-9 hours",
          description: "Long drive to trek starting point.",
        },
        {
          day: 2,
          title: "Trek to Machha Khola",
          altitude: "930m",
          duration: "6-7 hours",
          description: "Trek along Budhi Gandaki River.",
        },
        {
          day: 3,
          title: "Trek to Jagat",
          altitude: "1,340m",
          duration: "6-7 hours",
          description: "Continue along river through terraced fields.",
        },
        {
          day: 4,
          title: "Trek to Lokpa",
          altitude: "2,240m",
          duration: "6-7 hours",
          description: "Enter Tsum Valley, Tibetan influence begins.",
        },
        {
          day: 5,
          title: "Trek to Chumling",
          altitude: "2,386m",
          duration: "5-6 hours",
          description: "First village in Tsum Valley proper.",
        },
        {
          day: 6,
          title: "Trek to Chokhangparo",
          altitude: "3,010m",
          duration: "4-5 hours",
          description: "Continue up valley through traditional villages.",
        },
        {
          day: 7,
          title: "Trek to Nile",
          altitude: "3,361m",
          duration: "4-5 hours",
          description: "Higher altitude village with mountain views.",
        },
        {
          day: 8,
          title: "Trek to Mu Gompa",
          altitude: "3,700m",
          duration: "3-4 hours",
          description: "Reach highest monastery in Tsum Valley.",
        },
        {
          day: 9,
          title: "Explore Mu Gompa",
          altitude: "3,700m",
          duration: "Rest day",
          description: "Rest day exploring monastery and surroundings.",
        },
        {
          day: 10,
          title: "Trek to Burgi",
          altitude: "3,245m",
          duration: "4-5 hours",
          description: "Begin descent down valley.",
        },
        {
          day: 11,
          title: "Trek to Chumling",
          altitude: "2,386m",
          duration: "5-6 hours",
          description: "Return to Chumling village.",
        },
        {
          day: 12,
          title: "Trek to Philim",
          altitude: "1,570m",
          duration: "6-7 hours",
          description: "Exit Tsum Valley, return to main trail.",
        },
        {
          day: 13,
          title: "Trek to Jagat",
          altitude: "1,340m",
          duration: "5-6 hours",
          description: "Continue descent along Budhi Gandaki.",
        },
        {
          day: 14,
          title: "Trek to Soti Khola",
          altitude: "700m",
          duration: "6-7 hours",
          description: "Final day of trekking.",
        },
        {
          day: 15,
          title: "Drive to Kathmandu",
          altitude: "1,400m",
          duration: "8-9 hours",
          description: "Long drive back to Kathmandu.",
        },
      ],
    },
    "nar-phu-valley": {
      id: "nar-phu-valley",
      title: "Nar Phu Valley Trek",
      subtitle: "Remote Restricted Area Adventure",
      image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1920&h=800&fit=crop&sat=-10&hue=60",
      duration: "17 days",
      difficulty: "Challenging",
      maxAltitude: "5,416m",
      bestSeason: "March-May, September-November",
      price: "$1,599",
      region: "Annapurna",
      rating: 4.8,
      reviewCount: 45,
      description:
        "Trek to the remote restricted valleys of Nar and Phu, experiencing ancient Tibetan culture and crossing the challenging Kang La Pass.",
      highlights: [
        "Ancient Nar and Phu villages",
        "Kang La Pass crossing",
        "Tibetan Buddhist culture",
        "Remote wilderness",
        "Restricted area permit",
        "Unique landscapes",
      ],
      inclusions: [
        "Airport transfers",
        "Private vehicle transport",
        "All meals during trek",
        "Tea house/camping accommodation",
        "Professional guide and porter",
        "Restricted area permits",
        "All fees and taxes",
        "First aid kit",
      ],
      exclusions: [
        "International flights",
        "Nepal visa",
        "Hotel accommodation",
        "Personal equipment",
        "Insurance",
        "Personal expenses",
        "Tips",
        "Emergency evacuation",
      ],
      itinerary: [
        {
          day: 1,
          title: "Drive to Besisahar, Trek to Bhulbhule",
          altitude: "840m",
          duration: "6-7 hours",
          description: "Drive to Besisahar, begin trek along Marsyangdi.",
        },
        {
          day: 2,
          title: "Trek to Jagat",
          altitude: "1,300m",
          duration: "6-7 hours",
          description: "Trek through terraced fields and villages.",
        },
        {
          day: 3,
          title: "Trek to Dharapani",
          altitude: "1,860m",
          duration: "6-7 hours",
          description: "Enter restricted area, Tibetan influence begins.",
        },
        {
          day: 4,
          title: "Trek to Koto",
          altitude: "2,600m",
          duration: "6-7 hours",
          description: "Last village before entering Nar Phu valley.",
        },
        {
          day: 5,
          title: "Trek to Meta",
          altitude: "3,560m",
          duration: "6-7 hours",
          description: "Enter Nar Phu valley, dramatic landscape change.",
        },
        {
          day: 6,
          title: "Trek to Phu Village",
          altitude: "4,080m",
          duration: "4-5 hours",
          description: "Reach ancient village of Phu, Tibetan culture.",
        },
        {
          day: 7,
          title: "Explore Phu Village",
          altitude: "4,080m",
          duration: "Rest day",
          description: "Rest day exploring village and surroundings.",
        },
        {
          day: 8,
          title: "Trek to Nar Village",
          altitude: "4,110m",
          duration: "5-6 hours",
          description: "Trek to second ancient village of Nar.",
        },
        {
          day: 9,
          title: "Explore Nar Village",
          altitude: "4,110m",
          duration: "Rest day",
          description: "Rest day exploring Nar village and monastery.",
        },
        {
          day: 10,
          title: "Trek to Kang La Phedi",
          altitude: "4,530m",
          duration: "4-5 hours",
          description: "Base camp for Kang La Pass crossing.",
        },
        {
          day: 11,
          title: "Cross Kang La Pass to Ngawal",
          altitude: "5,416m",
          duration: "8-9 hours",
          description: "Challenging pass crossing, join Annapurna Circuit.",
        },
        {
          day: 12,
          title: "Trek to Manang",
          altitude: "3,519m",
          duration: "4-5 hours",
          description: "Descend to Manang valley for rest.",
        },
        {
          day: 13,
          title: "Trek to Yak Kharka",
          altitude: "4,018m",
          duration: "4-5 hours",
          description: "Continue on Annapurna Circuit route.",
        },
        {
          day: 14,
          title: "Trek to Thorong Phedi",
          altitude: "4,450m",
          duration: "3-4 hours",
          description: "Base for Thorong La Pass crossing.",
        },
        {
          day: 15,
          title: "Cross Thorong La to Muktinath",
          altitude: "5,416m",
          duration: "7-8 hours",
          description: "Cross famous Thorong La Pass to Muktinath.",
        },
        {
          day: 16,
          title: "Drive to Pokhara",
          altitude: "822m",
          duration: "6-7 hours",
          description: "Drive via Jomsom to Pokhara.",
        },
      ],
    },
    "dolpo-trek": {
      id: "dolpo-trek",
      title: "Upper Dolpo Trek",
      subtitle: "Remote Trans-Himalayan Adventure",
      image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1920&h=800&fit=crop&sat=-20&hue=45",
      duration: "24 days",
      difficulty: "Strenuous",
      maxAltitude: "5,360m",
      bestSeason: "June-September",
      price: "$2,499",
      region: "Dolpo",
      rating: 4.9,
      reviewCount: 23,
      description:
        "Ultimate remote adventure through Nepal's largest district, featuring the stunning Shey Phoksundo Lake and ancient Bon Buddhist culture.",
      highlights: [
        "Shey Phoksundo Lake",
        "Crystal Mountain pilgrimage",
        "Ancient Bon Buddhist culture",
        "Trans-Himalayan landscape",
        "Remote wilderness",
        "Tibetan plateau experience",
      ],
      inclusions: [
        "Airport transfers",
        "Domestic flights",
        "All meals during trek",
        "Camping accommodation",
        "Professional guide and crew",
        "Restricted area permits",
        "All fees and taxes",
        "First aid kit",
      ],
      exclusions: [
        "International flights",
        "Nepal visa",
        "Hotel accommodation",
        "Personal equipment",
        "Insurance",
        "Personal expenses",
        "Tips",
        "Emergency evacuation",
      ],
      itinerary: [
        {
          day: 1,
          title: "Fly to Nepalgunj",
          altitude: "150m",
          duration: "1 hour",
          description: "Fly from Kathmandu to Nepalgunj.",
        },
        {
          day: 2,
          title: "Fly to Juphal, Trek to Dunai",
          altitude: "2,140m",
          duration: "3-4 hours",
          description: "Fly to Juphal, trek to district headquarters Dunai.",
        },
        {
          day: 3,
          title: "Trek to Tarakot",
          altitude: "2,537m",
          duration: "6-7 hours",
          description: "Trek along Bheri River to ancient fort town.",
        },
        {
          day: 4,
          title: "Trek to Laini",
          altitude: "3,370m",
          duration: "6-7 hours",
          description: "Climb towards Numa La Pass base.",
        },
        {
          day: 5,
          title: "Cross Numa La Pass to Pelung Tang",
          altitude: "5,190m",
          duration: "8-9 hours",
          description: "Cross first high pass with spectacular views.",
        },
        {
          day: 6,
          title: "Trek to Shey Gompa",
          altitude: "4,390m",
          duration: "3-4 hours",
          description: "Reach ancient monastery near Crystal Mountain.",
        },
        {
          day: 7,
          title: "Explore Shey Gompa",
          altitude: "4,390m",
          duration: "Rest day",
          description: "Rest day exploring monastery and Crystal Mountain.",
        },
        {
          day: 8,
          title: "Trek to Namduna Gaun",
          altitude: "4,800m",
          duration: "4-5 hours",
          description: "Trek towards Saldang La Pass.",
        },
        {
          day: 9,
          title: "Cross Saldang La to Saldang",
          altitude: "5,200m",
          duration: "6-7 hours",
          description: "Cross second high pass to Saldang village.",
        },
        {
          day: 10,
          title: "Trek to Yangze Gompa",
          altitude: "4,960m",
          duration: "4-5 hours",
          description: "Visit remote monastery in high valley.",
        },
        {
          day: 11,
          title: "Trek to Sibu",
          altitude: "4,560m",
          duration: "5-6 hours",
          description: "Continue through remote villages.",
        },
        {
          day: 12,
          title: "Trek to Jeng La Phedi",
          altitude: "4,900m",
          duration: "4-5 hours",
          description: "Base camp for Jeng La Pass.",
        },
        {
          day: 13,
          title: "Cross Jeng La to Tokyu Gaun",
          altitude: "5,090m",
          duration: "7-8 hours",
          description: "Cross third high pass of the trek.",
        },
        {
          day: 14,
          title: "Trek to Dho Tarap",
          altitude: "4,040m",
          duration: "5-6 hours",
          description: "Reach largest village in upper Dolpo.",
        },
        {
          day: 15,
          title: "Rest Day in Dho Tarap",
          altitude: "4,040m",
          duration: "Rest day",
          description: "Rest day exploring village and monastery.",
        },
        {
          day: 16,
          title: "Trek to Tarap Chu",
          altitude: "4,200m",
          duration: "5-6 hours",
          description: "Trek along Tarap River valley.",
        },
        {
          day: 17,
          title: "Trek to Kamakharka",
          altitude: "3,800m",
          duration: "6-7 hours",
          description: "Continue descent along river.",
        },
        {
          day: 18,
          title: "Trek to Khanigaon",
          altitude: "3,150m",
          duration: "5-6 hours",
          description: "Descend to lower altitude village.",
        },
        {
          day: 19,
          title: "Trek to Tarakot",
          altitude: "2,537m",
          duration: "6-7 hours",
          description: "Return to Tarakot for rest.",
        },
        {
          day: 20,
          title: "Trek to Dunai",
          altitude: "2,140m",
          duration: "5-6 hours",
          description: "Return to district headquarters.",
        },
        {
          day: 21,
          title: "Trek to Juphal",
          altitude: "2,475m",
          duration: "2-3 hours",
          description: "Short trek to airstrip.",
        },
        {
          day: 22,
          title: "Fly to Nepalgunj",
          altitude: "150m",
          duration: "30 minutes",
          description: "Flight back to Nepalgunj.",
        },
        {
          day: 23,
          title: "Fly to Kathmandu",
          altitude: "1,400m",
          duration: "1 hour",
          description: "Return flight to Kathmandu.",
        },
      ],
    },
    "kanchenjunga-base-camp": {
      id: "kanchenjunga-base-camp",
      title: "Kanchenjunga Base Camp Trek",
      subtitle: "Remote Trek to the Third Highest Peak",
      image: "https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=1920&h=800&fit=crop&sat=15&hue=160",
      duration: "22 days",
      difficulty: "Strenuous",
      maxAltitude: "5,143m",
      bestSeason: "March-May, September-November",
      price: "$1,999",
      region: "Kanchenjunga",
      rating: 4.8,
      reviewCount: 34,
      description:
        "Remote and challenging trek to both north and south base camps of Kanchenjunga, the world's third highest mountain, through pristine wilderness.",
      highlights: [
        "North and South Base Camps",
        "Third highest mountain",
        "Pristine wilderness",
        "Rare wildlife viewing",
        "Remote mountain culture",
        "Challenging adventure",
      ],
      inclusions: [
        "Airport transfers",
        "Domestic flights",
        "All meals during trek",
        "Tea house/camping accommodation",
        "Professional guide and crew",
        "Restricted area permits",
        "All fees and taxes",
        "First aid kit",
      ],
      exclusions: [
        "International flights",
        "Nepal visa",
        "Hotel accommodation",
        "Personal equipment",
        "Insurance",
        "Personal expenses",
        "Tips",
        "Emergency evacuation",
      ],
      itinerary: [
        {
          day: 1,
          title: "Fly to Bhadrapur, Drive to Ilam",
          altitude: "1,200m",
          duration: "6-7 hours",
          description: "Fly to eastern Nepal, drive to tea garden town.",
        },
        {
          day: 2,
          title: "Drive to Taplejung",
          altitude: "1,820m",
          duration: "6-7 hours",
          description: "Drive to trek starting point in mountains.",
        },
        {
          day: 3,
          title: "Trek to Mitlung",
          altitude: "921m",
          duration: "5-6 hours",
          description: "Begin trek descending to Tamur River.",
        },
        {
          day: 4,
          title: "Trek to Chirwa",
          altitude: "1,270m",
          duration: "6-7 hours",
          description: "Trek along river through subtropical forests.",
        },
        {
          day: 5,
          title: "Trek to Sekathum",
          altitude: "1,660m",
          duration: "6-7 hours",
          description: "Continue up valley, enter national park.",
        },
        {
          day: 6,
          title: "Trek to Amjilosa",
          altitude: "2,510m",
          duration: "5-6 hours",
          description: "Climb through rhododendron forests.",
        },
        {
          day: 7,
          title: "Trek to Gyabla",
          altitude: "2,730m",
          duration: "4-5 hours",
          description: "Enter alpine zone with mountain views.",
        },
        {
          day: 8,
          title: "Trek to Ghunsa",
          altitude: "3,595m",
          duration: "6-7 hours",
          description: "Reach main village in Kanchenjunga valley.",
        },
        {
          day: 9,
          title: "Acclimatization Day in Ghunsa",
          altitude: "3,595m",
          duration: "Rest day",
          description: "Rest day for acclimatization and exploration.",
        },
        {
          day: 10,
          title: "Trek to Kambachen",
          altitude: "4,050m",
          duration: "5-6 hours",
          description: "Trek higher up valley with glacier views.",
        },
        {
          day: 11,
          title: "Trek to Lhonak",
          altitude: "4,780m",
          duration: "4-5 hours",
          description: "High altitude camp near glaciers.",
        },
        {
          day: 12,
          title: "Trek to Pangpema (North Base Camp)",
          altitude: "5,143m",
          duration: "4-5 hours",
          description: "Reach north base camp of Kanchenjunga.",
        },
        {
          day: 13,
          title: "Explore Pangpema",
          altitude: "5,143m",
          duration: "Rest day",
          description: "Rest day exploring base camp area.",
        },
        {
          day: 14,
          title: "Trek to Kambachen",
          altitude: "4,050m",
          duration: "6-7 hours",
          description: "Begin descent from base camp.",
        },
        {
          day: 15,
          title: "Trek to Ghunsa",
          altitude: "3,595m",
          duration: "5-6 hours",
          description: "Return to Ghunsa village.",
        },
        {
          day: 16,
          title: "Trek to Sele La",
          altitude: "4,290m",
          duration: "6-7 hours",
          description: "Cross pass to reach south side.",
        },
        {
          day: 17,
          title: "Trek to Tseram",
          altitude: "3,870m",
          duration: "5-6 hours",
          description: "Descend to south side base camp area.",
        },
        {
          day: 18,
          title: "Trek to Ramche (South Base Camp)",
          altitude: "4,580m",
          duration: "4-5 hours",
          description: "Reach south base camp of Kanchenjunga.",
        },
        {
          day: 19,
          title: "Trek to Torongding",
          altitude: "2,995m",
          duration: "6-7 hours",
          description: "Begin long descent to lower elevations.",
        },
        {
          day: 20,
          title: "Trek to Yamphudin",
          altitude: "2,080m",
          duration: "5-6 hours",
          description: "Continue descent through forests.",
        },
        {
          day: 21,
          title: "Trek to Khebang, Drive to Taplejung",
          altitude: "1,915m",
          duration: "6-7 hours",
          description: "Final day of trekking, drive to Taplejung.",
        },
        {
          day: 22,
          title: "Fly to Kathmandu",
          altitude: "1,400m",
          duration: "1 hour",
          description: "Flight back to Kathmandu via Bhadrapur.",
        },
      ],
    },
    "makalu-base-camp": {
      id: "makalu-base-camp",
      title: "Makalu Base Camp Trek",
      subtitle: "Challenging Trek Through Pristine Wilderness",
      image: "https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=1920&h=800&fit=crop&sat=20&hue=190",
      duration: "20 days",
      difficulty: "Strenuous",
      maxAltitude: "4,870m",
      bestSeason: "March-May, September-November",
      price: "$1,799",
      region: "Makalu",
      rating: 4.7,
      reviewCount: 28,
      description:
        "Challenging trek through pristine wilderness to Makalu Base Camp, featuring diverse ecosystems from tropical to alpine zones.",
      highlights: [
        "Makalu Base Camp (4,870m)",
        "Barun Valley wilderness",
        "Diverse ecosystems",
        "Fifth highest mountain",
        "Remote adventure",
        "Pristine nature",
      ],
      inclusions: [
        "Airport transfers",
        "Domestic flights",
        "All meals during trek",
        "Tea house/camping accommodation",
        "Professional guide and crew",
        "All permits and fees",
        "First aid kit",
        "Government taxes",
      ],
      exclusions: [
        "International flights",
        "Nepal visa",
        "Hotel accommodation",
        "Personal equipment",
        "Insurance",
        "Personal expenses",
        "Tips",
        "Emergency evacuation",
      ],
      itinerary: [
        {
          day: 1,
          title: "Fly to Tumlingtar, Drive to Chichila",
          altitude: "1,980m",
          duration: "6-7 hours",
          description: "Fly to eastern Nepal, drive to trek start.",
        },
        {
          day: 2,
          title: "Trek to Num",
          altitude: "1,560m",
          duration: "6-7 hours",
          description: "Begin trek through terraced hillsides.",
        },
        {
          day: 3,
          title: "Trek to Seduwa",
          altitude: "1,500m",
          duration: "6-7 hours",
          description: "Trek through traditional villages.",
        },
        {
          day: 4,
          title: "Trek to Tashigaon",
          altitude: "2,100m",
          duration: "5-6 hours",
          description: "Last permanent settlement before wilderness.",
        },
        {
          day: 5,
          title: "Trek to Khongma Danda",
          altitude: "3,500m",
          duration: "6-7 hours",
          description: "Enter wilderness area, steep climb.",
        },
        {
          day: 6,
          title: "Acclimatization Day",
          altitude: "3,500m",
          duration: "Rest day",
          description: "Rest day for acclimatization.",
        },
        {
          day: 7,
          title: "Trek to Dobate",
          altitude: "3,650m",
          duration: "5-6 hours",
          description: "Trek through rhododendron forests.",
        },
        {
          day: 8,
          title: "Trek to Yangri Kharka",
          altitude: "3,557m",
          duration: "5-6 hours",
          description: "Beautiful meadows with mountain views.",
        },
        {
          day: 9,
          title: "Trek to Langmale Kharka",
          altitude: "4,410m",
          duration: "5-6 hours",
          description: "High altitude meadows, spectacular views.",
        },
        {
          day: 10,
          title: "Trek to Makalu Base Camp",
          altitude: "4,870m",
          duration: "4-5 hours",
          description: "Reach base camp of fifth highest mountain.",
        },
        {
          day: 11,
          title: "Explore Makalu Base Camp",
          altitude: "4,870m",
          duration: "Rest day",
          description: "Rest day exploring base camp area.",
        },
        {
          day: 12,
          title: "Trek to Yangri Kharka",
          altitude: "3,557m",
          duration: "6-7 hours",
          description: "Begin descent from base camp.",
        },
        {
          day: 13,
          title: "Trek to Dobate",
          altitude: "3,650m",
          duration: "4-5 hours",
          description: "Continue descent through forests.",
        },
        {
          day: 14,
          title: "Trek to Khongma Danda",
          altitude: "3,500m",
          duration: "5-6 hours",
          description: "Return to previous camp.",
        },
        {
          day: 15,
          title: "Trek to Tashigaon",
          altitude: "2,100m",
          duration: "6-7 hours",
          description: "Descend to last village.",
        },
        {
          day: 16,
          title: "Trek to Seduwa",
          altitude: "1,500m",
          duration: "5-6 hours",
          description: "Continue descent to lower elevations.",
        },
        {
          day: 17,
          title: "Trek to Num",
          altitude: "1,560m",
          duration: "6-7 hours",
          description: "Return to Num village.",
        },
        {
          day: 18,
          title: "Trek to Chichila",
          altitude: "1,980m",
          duration: "6-7 hours",
          description: "Final day of trekking.",
        },
        {
          day: 19,
          title: "Drive to Tumlingtar, Fly to Kathmandu",
          altitude: "1,400m",
          duration: "7-8 hours",
          description: "Drive to airport, fly to Kathmandu.",
        },
      ],
    },
    "khopra-danda": {
      id: "khopra-danda",
      title: "Khopra Danda Trek",
      subtitle: "Community-Based Trek with Stunning Views",
      image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1920&h=800&fit=crop&sat=30&hue=50",
      duration: "9 days",
      difficulty: "Moderate",
      maxAltitude: "3,660m",
      bestSeason: "March-May, September-November",
      price: "$799",
      region: "Annapurna",
      rating: 4.6,
      reviewCount: 112,
      description:
        "Community-based trek offering stunning views of Annapurna and Dhaulagiri ranges while supporting local communities through eco-tourism.",
      highlights: [
        "Khopra Ridge viewpoint",
        "Sacred Khayer Lake",
        "Community lodges",
        "Dhaulagiri views",
        "Sustainable tourism",
        "Off-the-beaten-path",
      ],
      inclusions: [
        "Airport transfers",
        "Private vehicle transport",
        "All meals during trek",
        "Community lodge accommodation",
        "Professional guide and porter",
        "All permits and fees",
        "First aid kit",
        "Government taxes",
      ],
      exclusions: [
        "International flights",
        "Nepal visa",
        "Hotel accommodation",
        "Personal equipment",
        "Insurance",
        "Personal expenses",
        "Tips",
        "Emergency evacuation",
      ],
      itinerary: [
        {
          day: 1,
          title: "Drive to Nayapul, Trek to Ghandruk",
          altitude: "1,940m",
          duration: "5-6 hours",
          description: "Drive to Nayapul, trek to beautiful Gurung village.",
        },
        {
          day: 2,
          title: "Trek to Tadapani",
          altitude: "2,630m",
          duration: "3-4 hours",
          description: "Climb through rhododendron forests to Tadapani.",
        },
        {
          day: 3,
          title: "Trek to Dobato",
          altitude: "3,350m",
          duration: "4-5 hours",
          description: "Continue climb with increasing mountain views.",
        },
        {
          day: 4,
          title: "Trek to Upper Chistibung",
          altitude: "2,975m",
          duration: "6-7 hours",
          description: "Trek to community lodge with spectacular views.",
        },
        {
          day: 5,
          title: "Trek to Khopra Danda",
          altitude: "3,660m",
          duration: "3-4 hours",
          description: "Reach Khopra Ridge with panoramic mountain views.",
        },
        {
          day: 6,
          title: "Hike to Khayer Lake",
          altitude: "4,660m",
          duration: "6-7 hours",
          description: "Day hike to sacred lake, return to Khopra.",
        },
        {
          day: 7,
          title: "Trek to Swanta Village",
          altitude: "2,200m",
          duration: "5-6 hours",
          description: "Descend to traditional village community lodge.",
        },
        {
          day: 8,
          title: "Trek to Ulleri",
          altitude: "1,960m",
          duration: "4-5 hours",
          description: "Continue descent through terraced fields.",
        },
        {
          day: 9,
          title: "Trek to Nayapul, Drive to Pokhara",
          altitude: "1,070m",
          duration: "4-5 hours",
          description: "Final day of trekking, drive to Pokhara.",
        },
      ],
    },
  }

  return treks[slug as keyof typeof treks] || null
}

export async function generateMetadata({ params }: { params: { slug: string } }) {
  const trek = getTrekData(params.slug)

  if (!trek) {
    return {
      title: "Trek Not Found - NepTrek",
    }
  }

  return {
    title: `${trek.title} - NepTrek | ${trek.duration} Himalayan Adventure`,
    description: trek.description,
  }
}

export default function TrekDetailPage({ params }: { params: { slug: string } }) {
  const trek = getTrekData(params.slug)

  if (!trek) {
    notFound()
  }

  return (
    <div className="min-h-screen">
      <Navigation />
      <main>
        <TrekHero trek={trek} />
        <TrekItinerary itinerary={trek.itinerary} />
        <TrekInclusions inclusions={trek.inclusions} exclusions={trek.exclusions} />
        <TrekMap />
        <TrekFAQ />
        <TrekBooking trek={trek} />
      </main>
      <Footer />
    </div>
  )
}
